version: '3.7'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASS}"
      MONGO_INITDB_DATABASE: catalog
    networks:
      - xfusion-python-api

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "${MONGODB_EXPRESS_PORT}:${MONGODB_EXPRESS_PORT}"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER}"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASS}"
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - xfusion-python-api
    depends_on: 
      - mongodb

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: xfusion-python-api
    restart: unless-stopped
    ports:
      - "${XFUSION_API_PORT}:80"
    environment:
      XFUSION_API_PORT: "${XFUSION_API_PORT}"
      MONGODB_HOST: "${MONGODB_HOST}"
      MONGODB_USER: "${MONGODB_USER}"
      MONGODB_PASS: "${MONGODB_PASS}"
    networks:
      - xfusion-python-api
    depends_on: 
      - mongodb

networks:
  xfusion-python-api:
    driver: bridge
