version: '3.7'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASS}"
      MONGO_INITDB_DATABASE: catalog
    networks:
      - python-api-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "${MONGODB_EXPRESS_PORT}:${MONGODB_EXPRESS_PORT}"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER}"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASS}"
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - python-api-network
    depends_on: 
      - mongodb

networks:
  python-api-network:
    driver: bridge
