version: '3.7'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    ports:
      - 27017:27017        
    environment:
      MONGO_INITDB_ROOT_USERNAME: "xfusion"
      MONGO_INITDB_ROOT_PASSWORD: "xfusion"
      MONGO_INITDB_DATABASE: catalog
      MONGODB_DATA_DIR: /data/db
    volumes:
      - "${XFUSION_MONGODB_DATA}:/data/db"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=xfusion
      - ME_CONFIG_MONGODB_ADMINPASSWORD=xfusion
      - ME_CONFIG_MONGODB_SERVER=mongodb
    
  api:
    container_name: xfusion-python-api
    build: 
      context: ./api
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    environment:
      MONGODB_HOST: mongodb
      MONGODB_USER: xfusion
      MONGODB_PASS: xfusion
    volumes:
      - "${XFUSION_ROOT_FOLDER}:/mnt/airflow"
    depends_on: 
      - mongodb

networks:
  default:
    name: xfusion-python-network
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  airflowdata:
    driver: local
